import { boolean } from "mathjs";
import { IShippingDetail } from "../../interfaces/shipping-detail.interface";
import { IShippingMethod } from "../../interfaces/shipping-method.interface";
import { IShipping } from "../../interfaces/shipping.interface";
import { ITax } from "../../interfaces/tax.interface";

export interface IInitialContextCheckoutState {
  phoneNumber: string;
  intlNumber: string;
  countryCode: string;
  countryId: string;
  productsObj: Array<any>;
  cart_id: any;
  platForm_bigCommerce: any;
  sku: string;
  shippingMethods: any;
  totalAmount: number;
  shippingPrice: string | any;
  shippingName: string | any;
  taxPrice: string;
  AuthToken: string;
  RequestHash: string;
  ChannelId: string;
  IsBIN: string;
  merchant_call_back_url: string;
  Currency: string;
  ReturnURL: string;
  MerchantId: string;
  StoreId: string;
  MerchantHash: string;
  MerchantUsername: string;
  MerchantPassword: string;
  TransactionTypeId: string;
  TransactionReferenceNumber: string;
  TransactionAmount: string;
  identityToken: string;
  productId: string;
  processingFee: string | number;
  productName: string;
  productQuantity: string;
  place_order_on_merchant_site: any;
  productPrice: string;
  src: string;
  url: string;
  currency: string;
  shippingValidate: boolean;
  cardInfo: any[];
  email: string;
  billingAddress: string;
  billingCity: string;
  bigCommerceURL: string;
  billingCountry: string;
  address: string;
  city: string;
  country: string;
  name: string;
  lastName: string;
  emailValidated: boolean;
  customerId: string;
  token: string;
  activeMethod: any;
  state: string;
  shippingCity: string;
  shippingCountry: string;
  shippingZip: string;
  billingZip: string;
  isGuest: boolean;
  isExistingUser: boolean;
  billingState: string;
  queryString: string;
  taxes: ITax[];
  // shippingDetails: IShippingDetail[];
  shippingDetails: any;
  newShippingDetails: any;
  discountedAmount: number;
  couponCode: string;
  isCouponApplied: boolean;
  encrypted: any[];
  packageSelectedQP: string;
  checkout_url: string;
  orderStatus: string;
  cnic: string;
  selectedBank: string;
  prodAmount: string;
  banks: any[];
  accountNumber: string;
  orderId: string;
  trackingId: string;
  surveyOpen: Boolean;
  finishSurveyOpen: Boolean;
  shorten_url: string;
  meta: string;
  isTez: number;
  storeType: string;
  callBackUrl: string;
  redirectUrl: string;
  merchantEndRequest: string;
  merchantOrderId: string;
  is4gives: boolean;
  selectedShipping: any;
  isStackBuilderEnabled: any;
  is_headless: any;
  zipCode: any;
  merchantWalletIsEnabled: boolean;
  merchantWalletFeePercentage: any;
  walletBalance: number;
  abandonedCartCheck: boolean;
  cartSessionID: any;
  walletToggleButtonCheck: any;
  payFastPackageID: any;
  walletName: any;
  bankName: any;
  walletID: any;
  bankID: any;
  payFastData: any;
  payFastDetails: any;
  payFastScreen: number;
  GoogleAnalyticsCred: any;
  vaultPackageID: any;
  skyFlow: any;
  collectContainer: any;
  card_number: any;
  card_cvv: any;
  card_expiry_month: any;
  card_expiry_year: any;
  card_skyflow_id: any;
  card_pin_id: any;
  epValidation: any;
  newSessionID: any;
  shippingAddress: any;
  mall_ID: any;
  signIn1cAuthStatus: any;
  SignInRequestId: any;
  globalCartObject: any;
  globalCartTotalAmount: any;
  store_type: any;
  invoice_id: any;
  invoiceId: any;
  AlfalahHTMLSnippet: any;
  signIn1cAuthcheck: any;
  headless_url: any;
  shipping_flag: any;
  tax_flag: any;
  link_id: any;
  phone_number_mall: any;
  guest_checkout: any;
  rudderStackID: any;
  userCnic: string;
  min: number;
  max: number;
  wordUrl: any;
  phoneNumberUrl: any;
  platform_fee: number;
  merchant_order_id: any;
  totalProccessingFee: string | number;
  placeOrderError: string;
  ipAddress: string;
  isEventsEnabled: boolean;
  MerchantUserId: number;
  methods: any;
  paymentMethods: any;
  checkout_anonymous_id: number;
  user_type: number;
  line_items: any;
  buttonDisabled: boolean;
  selectedMerchants: [];
  mall_taxes: [];
  shippingdetailsAPI: any;
  line_items_event: [];
  time_stamp: any;
}

export const checkoutInitialState: IInitialContextCheckoutState = {
  time_stamp: null,
  line_items_event: [],
  shippingdetailsAPI: [],
  mall_taxes: [],
  selectedMerchants: [],
  buttonDisabled: true,
  line_items: [],
  user_type: 0,
  checkout_anonymous_id: 0,
  paymentMethods: [],
  methods: "",
  MerchantUserId: 0,
  isEventsEnabled: false,
  ipAddress: "",
  merchant_order_id: "",
  phoneNumber: "",
  intlNumber: "",
  platform_fee: 0,
  totalProccessingFee: 0,
  countryCode: "",
  countryId: "",
  productsObj: [],
  shippingMethods: [],
  totalAmount: 0,
  shippingPrice: "",
  shippingName: "",
  taxPrice: "",
  processingFee: "",
  identityToken: "",
  productId: "",
  productName: "",
  productQuantity: "",
  productPrice: "",
  src: "",
  AuthToken: "",
  RequestHash: "",
  ChannelId: "",
  IsBIN: "",
  Currency: "",
  ReturnURL: "",
  MerchantId: "",
  StoreId: "",
  MerchantHash: "",
  prodAmount: "",
  MerchantUsername: "",
  MerchantPassword: "",
  TransactionTypeId: "",
  TransactionReferenceNumber: "",
  TransactionAmount: "",
  place_order_on_merchant_site: "",
  bigCommerceURL: "",
  merchant_call_back_url: "",
  url: "",
  currency: "",
  shippingValidate: false,
  cardInfo: [],
  email: "",
  address: "",
  billingAddress: "",
  billingCity: "",
  billingCountry: "",
  city: "",
  country: "",
  lastName: "",
  name: "",
  emailValidated: true,
  customerId: "",
  token: "",
  activeMethod: "",
  state: "",
  shippingCity: "",
  shippingCountry: "",
  billingZip: "",
  shippingZip: "",
  isGuest: false,
  isExistingUser: false,
  billingState: "",
  queryString: "",
  taxes: [],
  cart_id: "",
  platForm_bigCommerce: "",
  sku: "",
  shippingDetails: [],
  discountedAmount: 0,
  couponCode: "",
  isCouponApplied: false,
  encrypted: [],
  packageSelectedQP: "",
  checkout_url: "",
  orderStatus: "",
  cnic: "",
  userCnic: "",
  selectedBank: "",
  banks: [],
  accountNumber: "",
  orderId: "",
  trackingId: "",
  surveyOpen: false,
  finishSurveyOpen: false,
  shorten_url: "",
  meta: "",
  isTez: 2,
  storeType: "",
  callBackUrl: "",
  redirectUrl: "",
  merchantEndRequest: "",
  merchantOrderId: "",
  is4gives: false,
  selectedShipping: null,
  isStackBuilderEnabled: "",
  is_headless: "",
  zipCode: "",
  merchantWalletIsEnabled: false,
  merchantWalletFeePercentage: "",
  walletBalance: 0,
  abandonedCartCheck: false,
  cartSessionID: "",
  walletToggleButtonCheck: "",
  payFastPackageID: "",
  walletName: "",
  bankName: "",
  walletID: "",
  bankID: "",
  payFastData: "",
  payFastDetails: [],
  payFastScreen: 1,
  GoogleAnalyticsCred: "",
  vaultPackageID: "",
  newShippingDetails: [],
  skyFlow: "",
  collectContainer: "",
  card_number: "",
  card_cvv: "",
  card_expiry_month: "",
  card_expiry_year: "",
  card_skyflow_id: "",
  card_pin_id: "",
  epValidation: "",
  newSessionID: "",
  shippingAddress: "",
  mall_ID: "",
  signIn1cAuthStatus: null,
  SignInRequestId: null,
  globalCartObject: [],
  globalCartTotalAmount: 0,
  store_type: "",
  invoice_id: "",
  invoiceId: "",
  AlfalahHTMLSnippet: "",
  signIn1cAuthcheck: 0,
  headless_url: "",
  shipping_flag: "",
  tax_flag: "",
  link_id: "",
  phone_number_mall: "",
  guest_checkout: "",
  rudderStackID: "",
  min: 0,
  max: 0,
  wordUrl: "",
  phoneNumberUrl: "",
  placeOrderError: "",
};
